FROM node:15.10.0-alpine3.10

EXPOSE 5000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json package.json
RUN npm install
RUN npm install -g serve
RUN npm install react-scripts@4.0.3 -g
RUN npm run build
COPY . .


CMD ["serve", "-s", "build"]
